//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryVoteMVC.Resources.Login {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotteryVoteMVC.Resources.Login.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎来到各级代理登录 的本地化字符串。
        /// </summary>
        public static string AgentWelcomeString {
            get {
                return ResourceManager.GetString("AgentWelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同意 的本地化字符串。
        /// </summary>
        public static string agree {
            get {
                return ResourceManager.GetString("agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户一经在公司开户或投注，即视为已接受这些规则。 的本地化字符串。
        /// </summary>
        public static string Agreement1 {
            get {
                return ResourceManager.GetString("Agreement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如因在本网站投注触犯当地法律，本公司概不负责。 的本地化字符串。
        /// </summary>
        public static string Agreement10 {
            get {
                return ResourceManager.GetString("Agreement10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Agreement11 {
            get {
                return ResourceManager.GetString("Agreement11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果客户怀疑自己的资料被盗用，应立即通知本公司，并更改个人详细资料，且之前所有使用的使用者名称及密码将全部无效。 的本地化字符串。
        /// </summary>
        public static string Agreement2 {
            get {
                return ResourceManager.GetString("Agreement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户有责任确保自己的账户及登入资料的保密性。在本网站上以个人的使用者名称及密码进行的任何网上投注将被视为有效。 的本地化字符串。
        /// </summary>
        public static string Agreement3 {
            get {
                return ResourceManager.GetString("Agreement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注之后需等待下注成功信息出现方为完成下注。 的本地化字符串。
        /// </summary>
        public static string Agreement4 {
            get {
                return ResourceManager.GetString("Agreement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为避免发生争议，下注后请到【下注状况】里查看实际下注情况。 的本地化字符串。
        /// </summary>
        public static string Agreement5 {
            get {
                return ResourceManager.GetString("Agreement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有投注产品所公布折扣及赔率当出现任何输入错误或非故意人为失误，公司保留改正错误和按正确赔率结算投注的权利。 的本地化字符串。
        /// </summary>
        public static string Agreement6 {
            get {
                return ResourceManager.GetString("Agreement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任何条件更改及投诉必须在当期开奖前提出。 的本地化字符串。
        /// </summary>
        public static string Agreement7 {
            get {
                return ResourceManager.GetString("Agreement7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公布的所有赔率为浮动赔率，派彩时的赔率将以本公司确认投注时的赔率为准。 的本地化字符串。
        /// </summary>
        public static string Agreement8 {
            get {
                return ResourceManager.GetString("Agreement8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如本公司察觉客户投注状况异常，有权立即中止客户投注；在本公司中止下注前，客户的所有投注仍然有效，不得要求取消或延迟交收，不得有任何异议。 的本地化字符串。
        /// </summary>
        public static string Agreement9 {
            get {
                return ResourceManager.GetString("Agreement9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不同意 的本地化字符串。
        /// </summary>
        public static string Disagree {
            get {
                return ResourceManager.GetString("Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string LoginFaild {
            get {
                return ResourceManager.GetString("LoginFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string LoginField {
            get {
                return ResourceManager.GetString("LoginField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐号密码错误! 的本地化字符串。
        /// </summary>
        public static string UserNamePasswordFaild {
            get {
                return ResourceManager.GetString("UserNamePasswordFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误! 的本地化字符串。
        /// </summary>
        public static string VerifyCodeError {
            get {
                return ResourceManager.GetString("VerifyCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎来到用户登录 的本地化字符串。
        /// </summary>
        public static string WelcomeString {
            get {
                return ResourceManager.GetString("WelcomeString", resourceCulture);
            }
        }
    }
}
