var resource =
{
    PleaseCheckContent: "请检查下注内容是否正确!",
    PleaseCheckRowContent: "请检查第{0}行的下注内容是否正确!",
    PleaseInputCorrectNum: "请输入正确的号码!",
    MustBetSpecificGameType:"请确保第{0}行必须有{1}D玩法!",
    HaventEnoughtCredit: "您的余额不足以下注",
    ExistSameNum: "存在多个{0}",
    NumNoEnoughLen:"号码{0}长度未满{1}",
    Not2DNum: "不是一个2D号码!",
    Not3DNum: "不是一个3D号码!",
    Not4DNum: "不是一个4D号码!",
    Not5DNum: "不是一个5D号码!",
    InvalidNum: "无效数字",
    NotValidNum: " 不是一个有效的号码!",
    NotSupportGamePlay: "不支持游戏玩法!",
    Clear: "清除",
    Sunday: "星期日",
    Monday: "星期一",
    Tuesday: "星期二",
    Wednesday: "星期三",
    Thursday: "星期四",
    Friday: "星期五",
    Saturday: "星期六",
    Bet: "投注",
    Accept: "接受",
    NotAccept: "未接受",
    DropWater: "跌水",
    Success: "成功",
    Error:"错误",
    Failed: "失败",
    Add: "添加",
    Edit: "编辑",
    Delete: "删除",
    Expand: "展开",
    Collapse: "收起"
};