var resource =
{
    PleaseCheckContent: "vui lòng kiểm tra lại nội dung đúng hay sai",
    PleaseCheckRowContent: "vui lòng kiểm tra lại nội dung số đặt {0}đúng hay sai",
    PleaseInputCorrectNum: "xin nhập số chính xác",
    MustBetSpecificGameType: " Hãy chắc chắn rằng {0} hàng {1} D, trò chơi được chơi!",
    HaventEnoughtCredit: " Số dư của bạn là không đủ để đặt cược",
    ExistSameNum: " Có nhiều {0}",
    NumNoEnoughLen: "The length of the number {0} under {1}",
    Not2DNum: "nhập số 2d không chính xác",
    Not3DNum: "nhập số 3d không chính xác",
    Not4DNum: "nhập số 4d không chính xác",
    Not5DNum: "nhập số 5d không chính xác",
    InvalidNum: "số không chính xác",
    NotValidNum: " số này không có giá trị",
    NotSupportGamePlay: "mạng không hộ trợ",
    Clear: "Clear",
    Sunday: "Chủ Nhật",
    Monday: "Thứ hai",
    Tuesday: "Thứ ba",
    Wednesday: "Thứ tư",
    Thursday: "thứ năm",
    Friday: "Thứ Sáu",
    Saturday: "thứ bảy",
    Bet: "cá cược",
    Accept: "chấp nhận",
    NotAccept: "không chấp nhận",
    DropWater: "Trừ cò",
    Success: "Thành công",
    Error:"Error",
    Failed: "Failed",
    Add: "Thêm vào",
    Edit: "Chỉnh sửa",
    Delete: "Xóa",
    Expand: "Mở rộng",
    Collapse: "Thu gọn"
};