//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryVoteMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotteryVoteMVC.Resources.AuthResource", typeof(AuthResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string AccountController {
            get {
                return ResourceManager.GetString("AccountController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户(具体动作) 的本地化字符串。
        /// </summary>
        public static string AddUserAction {
            get {
                return ResourceManager.GetString("AddUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户(视图) 的本地化字符串。
        /// </summary>
        public static string AddUserView {
            get {
                return ResourceManager.GetString("AddUserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消报表 的本地化字符串。
        /// </summary>
        public static string CancelReport {
            get {
                return ResourceManager.GetString("CancelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 佣金管理 的本地化字符串。
        /// </summary>
        public static string CommissionController {
            get {
                return ResourceManager.GetString("CommissionController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户(具体动作) 的本地化字符串。
        /// </summary>
        public static string CreateUserAction {
            get {
                return ResourceManager.GetString("CreateUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户(视图) 的本地化字符串。
        /// </summary>
        public static string CreateUserView {
            get {
                return ResourceManager.GetString("CreateUserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 各级下注报表 的本地化字符串。
        /// </summary>
        public static string EachLevelReport {
            get {
                return ResourceManager.GetString("EachLevelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户下注限制 的本地化字符串。
        /// </summary>
        public static string EditBetLimit {
            get {
                return ResourceManager.GetString("EditBetLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户游戏限制 的本地化字符串。
        /// </summary>
        public static string EditGameLimit {
            get {
                return ResourceManager.GetString("EditGameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户(具体动作) 的本地化字符串。
        /// </summary>
        public static string EditUserAction {
            get {
                return ResourceManager.GetString("EditUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户佣金(具体操作) 的本地化字符串。
        /// </summary>
        public static string EditUserCommAction {
            get {
                return ResourceManager.GetString("EditUserCommAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户佣金(视图) 的本地化字符串。
        /// </summary>
        public static string EditUserCommView {
            get {
                return ResourceManager.GetString("EditUserCommView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户(视图) 的本地化字符串。
        /// </summary>
        public static string EditUserView {
            get {
                return ResourceManager.GetString("EditUserView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏限制 的本地化字符串。
        /// </summary>
        public static string LimitController {
            get {
                return ResourceManager.GetString("LimitController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号码统计 的本地化字符串。
        /// </summary>
        public static string NumAmountRanking {
            get {
                return ResourceManager.GetString("NumAmountRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注单管理 的本地化字符串。
        /// </summary>
        public static string OrderController {
            get {
                return ResourceManager.GetString("OrderController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表管理 的本地化字符串。
        /// </summary>
        public static string ReportController {
            get {
                return ResourceManager.GetString("ReportController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索用户 的本地化字符串。
        /// </summary>
        public static string SearchAccount {
            get {
                return ResourceManager.GetString("SearchAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大注单管理 的本地化字符串。
        /// </summary>
        public static string SheetController {
            get {
                return ResourceManager.GetString("SheetController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用用户 的本地化字符串。
        /// </summary>
        public static string StartUser {
            get {
                return ResourceManager.GetString("StartUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用用户 的本地化字符串。
        /// </summary>
        public static string StopUser {
            get {
                return ResourceManager.GetString("StopUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string ViewAccount {
            get {
                return ResourceManager.GetString("ViewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看所有注单 的本地化字符串。
        /// </summary>
        public static string ViewAllOrder {
            get {
                return ResourceManager.GetString("ViewAllOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看下属用户 的本地化字符串。
        /// </summary>
        public static string ViewChild {
            get {
                return ResourceManager.GetString("ViewChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看用户游戏限制 的本地化字符串。
        /// </summary>
        public static string ViewLimit {
            get {
                return ResourceManager.GetString("ViewLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看子用户 的本地化字符串。
        /// </summary>
        public static string ViewShadow {
            get {
                return ResourceManager.GetString("ViewShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看所有注单 的本地化字符串。
        /// </summary>
        public static string ViewSheets {
            get {
                return ResourceManager.GetString("ViewSheets", resourceCulture);
            }
        }
    }
}
