//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryVoteMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BetRule {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BetRule() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotteryVoteMVC.Resources.BetRule", typeof(BetRule).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 在18A, 18B和 18C公司中,AA和BB都至少有一次等于&apos;2D-包组&apos;中的数字串 的本地化字符串。
        /// </summary>
        public static string ABPL2WinLaw {
            get {
                return ResourceManager.GetString("ABPL2WinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注 的本地化字符串。
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注类型 的本地化字符串。
        /// </summary>
        public static string BetType {
            get {
                return ResourceManager.GetString("BetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XX至少有一次等于‘2D-头尾’中的数字串 的本地化字符串。
        /// </summary>
        public static string D2HeadLastWinLaw {
            get {
                return ResourceManager.GetString("D2HeadLastWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XX至少有一次等于‘2D-头’中的数字串 的本地化字符串。
        /// </summary>
        public static string D2HeadWinLaw {
            get {
                return ResourceManager.GetString("D2HeadWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XX至少有一次等于‘2D-尾’中的数字串 的本地化字符串。
        /// </summary>
        public static string D2LastWinLaw {
            get {
                return ResourceManager.GetString("D2LastWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XX至少有一次等于‘2D-包组7’中的数字串 的本地化字符串。
        /// </summary>
        public static string D2Roll7WinLaw {
            get {
                return ResourceManager.GetString("D2Roll7WinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XX至少有一次等于‘2D-包组’中的数字串 的本地化字符串。
        /// </summary>
        public static string D2RollWinLaw {
            get {
                return ResourceManager.GetString("D2RollWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXX至少有一次等于‘3D-头尾’中的数字串 的本地化字符串。
        /// </summary>
        public static string D3HeadLastWinLaw {
            get {
                return ResourceManager.GetString("D3HeadLastWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXX至少有一次等于‘3D-头’中的数字串 的本地化字符串。
        /// </summary>
        public static string D3HeadWinLaw {
            get {
                return ResourceManager.GetString("D3HeadWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXX至少有一次等于‘3D-尾’中的数字串 的本地化字符串。
        /// </summary>
        public static string D3LastWinLaw {
            get {
                return ResourceManager.GetString("D3LastWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXX至少有一次等于‘3D-包组7’中的数字串 的本地化字符串。
        /// </summary>
        public static string D3Roll7WinLaw {
            get {
                return ResourceManager.GetString("D3Roll7WinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXX至少有一次等于‘3D-包组’中的数字串 的本地化字符串。
        /// </summary>
        public static string D3RollWinLaw {
            get {
                return ResourceManager.GetString("D3RollWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXXX至少有一次等于‘4D-尾’中的数字串 的本地化字符串。
        /// </summary>
        public static string D4LastWinLaw {
            get {
                return ResourceManager.GetString("D4LastWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XXXX至少有一次等于‘4D-包组’中的数字串 的本地化字符串。
        /// </summary>
        public static string D4RollWinLaw {
            get {
                return ResourceManager.GetString("D4RollWinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示例 的本地化字符串。
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中奖金额=下注*赔率*倍数 的本地化字符串。
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩法说明 的本地化字符串。
        /// </summary>
        public static string GameDescript {
            get {
                return ResourceManager.GetString("GameDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 越南彩2(越南彩票的一般玩法)是基于越南传统型彩票的开奖结果。彩票由多间公司开出，名称为“Hanoi”的公司所开出的彩票有27个数字字符串，其他公司则为18个字符串。下注时只需写下数字串和选择游戏类型，如果你在正确位置上押中正确的数字串，你就赢。 的本地化字符串。
        /// </summary>
        public static string GameDescription {
            get {
                return ResourceManager.GetString("GameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 &amp; 范围 的本地化字符串。
        /// </summary>
        public static string LocationAndRange {
            get {
                return ResourceManager.GetString("LocationAndRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倍数 的本地化字符串。
        /// </summary>
        public static string Multiple {
            get {
                return ResourceManager.GetString("Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AA和BB都至少有一次等于&apos;2D-包组&apos;中的数字串 的本地化字符串。
        /// </summary>
        public static string Pl2WinLaw {
            get {
                return ResourceManager.GetString("Pl2WinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AA、BB和CC都至少有一次等于&apos;2D-包组&apos;中的数字串 的本地化字符串。
        /// </summary>
        public static string Pl3WinLaw {
            get {
                return ResourceManager.GetString("Pl3WinLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结果 的本地化字符串。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规则 的本地化字符串。
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ’头‘ 包括彩票结果中的n-位数字串，n代表你所下注的数字串的长度； 的本地化字符串。
        /// </summary>
        public static string Rule1 {
            get {
                return ResourceManager.GetString("Rule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ’尾‘ 包括彩票结果中最后一个数字串的倒数n个数字； 的本地化字符串。
        /// </summary>
        public static string Rule2 {
            get {
                return ResourceManager.GetString("Rule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ’头尾‘包括 ’头‘ 和 ’尾‘ 所包含的所有数字串； 的本地化字符串。
        /// </summary>
        public static string Rule3 {
            get {
                return ResourceManager.GetString("Rule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ‘包组’ 包括彩票结果中所有数字串的倒数n个数字； 的本地化字符串。
        /// </summary>
        public static string Rule4 {
            get {
                return ResourceManager.GetString("Rule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ‘包组7’ 包括彩票结果中第一个到第六个或者是最后一个数字串的倒数n个数字； 的本地化字符串。
        /// </summary>
        public static string Rule5 {
            get {
                return ResourceManager.GetString("Rule5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于‘包组过关2’和‘包组过关3’，我们使用‘2D-包组’的数字串检查用户的下注的数字串。如果你下注 AA#BB，例如AA在’2D-包组‘出现一次，BB出现三次，那么倍数是1；如果AA出现三次，BB出现两次，那么倍数也是2。 的本地化字符串。
        /// </summary>
        public static string Rule6 {
            get {
                return ResourceManager.GetString("Rule6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于‘ABC’包组过关2，我们使用在18A, 18B和 18C公司中‘2D-包组’的数字串检查用户的下注的数字串。如果你下注 AA#BB，例如AA在’2D-包组‘出现一次，BB出现三次，那么倍数是1；如果AA出现三次，BB出现两次，那么倍数是2。 的本地化字符串。
        /// </summary>
        public static string Rule7 {
            get {
                return ResourceManager.GetString("Rule7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中奖金额 的本地化字符串。
        /// </summary>
        public static string WinAmount {
            get {
                return ResourceManager.GetString("WinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赢的条件 的本地化字符串。
        /// </summary>
        public static string WinLaw {
            get {
                return ResourceManager.GetString("WinLaw", resourceCulture);
            }
        }
    }
}
