//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryVoteMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Log {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Log() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotteryVoteMVC.Resources.Log", typeof(Log).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加佣金组 的本地化字符串。
        /// </summary>
        public static string AddCommGroup {
            get {
                return ResourceManager.GetString("AddCommGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加开奖公司 的本地化字符串。
        /// </summary>
        public static string AddLotteryCompany {
            get {
                return ResourceManager.GetString("AddLotteryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加子用户 的本地化字符串。
        /// </summary>
        public static string AddShadow {
            get {
                return ResourceManager.GetString("AddShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户 的本地化字符串。
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑子用户 的本地化字符串。
        /// </summary>
        public static string EditShadow {
            get {
                return ResourceManager.GetString("EditShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户 的本地化字符串。
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移出佣金组 的本地化字符串。
        /// </summary>
        public static string RemoveCommGroup {
            get {
                return ResourceManager.GetString("RemoveCommGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移出开奖公司 的本地化字符串。
        /// </summary>
        public static string RemoveLotteryCompany {
            get {
                return ResourceManager.GetString("RemoveLotteryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用用户 的本地化字符串。
        /// </summary>
        public static string StartUser {
            get {
                return ResourceManager.GetString("StartUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停用户 的本地化字符串。
        /// </summary>
        public static string StopUser {
            get {
                return ResourceManager.GetString("StopUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新佣金组 的本地化字符串。
        /// </summary>
        public static string UpdateCommGroup {
            get {
                return ResourceManager.GetString("UpdateCommGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新开奖公司 的本地化字符串。
        /// </summary>
        public static string UpdateLotteryCompany {
            get {
                return ResourceManager.GetString("UpdateLotteryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新开奖公司开奖时间 的本地化字符串。
        /// </summary>
        public static string UpdateLotteryCompanyCycle {
            get {
                return ResourceManager.GetString("UpdateLotteryCompanyCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新用户下注限制 的本地化字符串。
        /// </summary>
        public static string UpdateUserBetLimit {
            get {
                return ResourceManager.GetString("UpdateUserBetLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新用户佣金 的本地化字符串。
        /// </summary>
        public static string UpdateUserComm {
            get {
                return ResourceManager.GetString("UpdateUserComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新用户游戏限制 的本地化字符串。
        /// </summary>
        public static string UpdateUserGameLimit {
            get {
                return ResourceManager.GetString("UpdateUserGameLimit", resourceCulture);
            }
        }
    }
}
