//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryVoteMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LotteryVoteMVC.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 缩写 的本地化字符串。
        /// </summary>
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受 的本地化字符串。
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日志 的本地化字符串。
        /// </summary>
        public static string ActionLog {
            get {
                return ResourceManager.GetString("ActionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加上限 的本地化字符串。
        /// </summary>
        public static string AddLimit {
            get {
                return ResourceManager.GetString("AddLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加开奖结果 的本地化字符串。
        /// </summary>
        public static string AddLotteryResult {
            get {
                return ResourceManager.GetString("AddLotteryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理 的本地化字符串。
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在 的本地化字符串。
        /// </summary>
        public static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        public static string Asc {
            get {
                return ResourceManager.GetString("Asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统自动跌水 的本地化字符串。
        /// </summary>
        public static string AutoDropWater {
            get {
                return ResourceManager.GetString("AutoDropWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动刷新 的本地化字符串。
        /// </summary>
        public static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用额度 的本地化字符串。
        /// </summary>
        public static string AvailableGivenCredit {
            get {
                return ResourceManager.GetString("AvailableGivenCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回首页 的本地化字符串。
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结余报表 的本地化字符串。
        /// </summary>
        public static string BalReport {
            get {
                return ResourceManager.GetString("BalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员连注限制 的本地化字符串。
        /// </summary>
        public static string BatterBetLimit {
            get {
                return ResourceManager.GetString("BatterBetLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投注 的本地化字符串。
        /// </summary>
        public static string Bet {
            get {
                return ResourceManager.GetString("Bet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注单数 的本地化字符串。
        /// </summary>
        public static string BetCount {
            get {
                return ResourceManager.GetString("BetCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注金额 的本地化字符串。
        /// </summary>
        public static string BetCredit {
            get {
                return ResourceManager.GetString("BetCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注限制 的本地化字符串。
        /// </summary>
        public static string BetLimit {
            get {
                return ResourceManager.GetString("BetLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注列表 的本地化字符串。
        /// </summary>
        public static string BetList {
            get {
                return ResourceManager.GetString("BetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投注规则 的本地化字符串。
        /// </summary>
        public static string BetRule {
            get {
                return ResourceManager.GetString("BetRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注单列表 的本地化字符串。
        /// </summary>
        public static string BetSheetList {
            get {
                return ResourceManager.GetString("BetSheetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注 的本地化字符串。
        /// </summary>
        public static string BetVote {
            get {
                return ResourceManager.GetString("BetVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 的本地化字符串。
        /// </summary>
        public static string Big {
            get {
                return ResourceManager.GetString("Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消注单 的本地化字符串。
        /// </summary>
        public static string CancelList {
            get {
                return ResourceManager.GetString("CancelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消时间 的本地化字符串。
        /// </summary>
        public static string CancelTime {
            get {
                return ResourceManager.GetString("CancelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输赢 的本地化字符串。
        /// </summary>
        public static string CashBalance {
            get {
                return ResourceManager.GetString("CashBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中 的本地化字符串。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请检查输入的网址是否正确。 的本地化字符串。
        /// </summary>
        public static string CheckUrlCorrect {
            get {
                return ResourceManager.GetString("CheckUrlCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级总佣金 的本地化字符串。
        /// </summary>
        public static string ChildsTotalComm {
            get {
                return ResourceManager.GetString("ChildsTotalComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已关闭 的本地化字符串。
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关盘时间 的本地化字符串。
        /// </summary>
        public static string CloseTime {
            get {
                return ResourceManager.GetString("CloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收起 的本地化字符串。
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 佣金 的本地化字符串。
        /// </summary>
        public static string Comm {
            get {
                return ResourceManager.GetString("Comm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 佣金 的本地化字符串。
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司 的本地化字符串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司描述 的本地化字符串。
        /// </summary>
        public static string CompanyDescription {
            get {
                return ResourceManager.GetString("CompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司类型 的本地化字符串。
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该公司已结算，请尝试重新结算 的本地化字符串。
        /// </summary>
        public static string CompanyWasSettled {
            get {
                return ResourceManager.GetString("CompanyWasSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币 的本地化字符串。
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 化 的本地化字符串。
        /// </summary>
        public static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最终限制设置 的本地化字符串。
        /// </summary>
        public static string DefaultUpperLimit {
            get {
                return ResourceManager.GetString("DefaultUpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跌水 的本地化字符串。
        /// </summary>
        public static string DropWater {
            get {
                return ResourceManager.GetString("DropWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双双 的本地化字符串。
        /// </summary>
        public static string EvenEven {
            get {
                return ResourceManager.GetString("EvenEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双头 的本地化字符串。
        /// </summary>
        public static string EvenHead {
            get {
                return ResourceManager.GetString("EvenHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双尾 的本地化字符串。
        /// </summary>
        public static string EvenLast {
            get {
                return ResourceManager.GetString("EvenLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双单 的本地化字符串。
        /// </summary>
        public static string EvenOdd {
            get {
                return ResourceManager.GetString("EvenOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开 的本地化字符串。
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速下注 的本地化字符串。
        /// </summary>
        public static string FastBet {
            get {
                return ResourceManager.GetString("FastBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2D快速下注 的本地化字符串。
        /// </summary>
        public static string FastBet2D {
            get {
                return ResourceManager.GetString("FastBet2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D快速下注 的本地化字符串。
        /// </summary>
        public static string FastBet3D {
            get {
                return ResourceManager.GetString("FastBet3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字1 的本地化字符串。
        /// </summary>
        public static string FirstNum {
            get {
                return ResourceManager.GetString("FirstNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期五 的本地化字符串。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从 的本地化字符串。
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全数报表 的本地化字符串。
        /// </summary>
        public static string FullStatements {
            get {
                return ResourceManager.GetString("FullStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏限制 的本地化字符串。
        /// </summary>
        public static string GameLimit {
            get {
                return ResourceManager.GetString("GameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏玩法 的本地化字符串。
        /// </summary>
        public static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信用限额 的本地化字符串。
        /// </summary>
        public static string GivenCredit {
            get {
                return ResourceManager.GetString("GivenCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组名 的本地化字符串。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员 的本地化字符串。
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头 的本地化字符串。
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头尾 的本地化字符串。
        /// </summary>
        public static string HeadAndLast {
            get {
                return ResourceManager.GetString("HeadAndLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未激活 的本地化字符串。
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级净金额 的本地化字符串。
        /// </summary>
        public static string JuniorNetAmount {
            get {
                return ResourceManager.GetString("JuniorNetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级总输赢 的本地化字符串。
        /// </summary>
        public static string JuniorTotalWinLost {
            get {
                return ResourceManager.GetString("JuniorTotalWinLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级赢 的本地化字符串。
        /// </summary>
        public static string JuniorWin {
            get {
                return ResourceManager.GetString("JuniorWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾 的本地化字符串。
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登录时间 的本地化字符串。
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上月 的本地化字符串。
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上周 的本地化字符串。
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 限制 的本地化字符串。
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上限监控 的本地化字符串。
        /// </summary>
        public static string LimitMonitor {
            get {
                return ResourceManager.GetString("LimitMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的账户在别处登录，请重新登录！ 的本地化字符串。
        /// </summary>
        public static string LoginByOtherOne {
            get {
                return ResourceManager.GetString("LoginByOtherOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录日志 的本地化字符串。
        /// </summary>
        public static string LoginLog {
            get {
                return ResourceManager.GetString("LoginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输 的本地化字符串。
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开奖结果 的本地化字符串。
        /// </summary>
        public static string LotteryResult {
            get {
                return ResourceManager.GetString("LotteryResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市场 的本地化字符串。
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总代 的本地化字符串。
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大 的本地化字符串。
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级下注限制 的本地化字符串。
        /// </summary>
        public static string MemberBetLimit {
            get {
                return ResourceManager.GetString("MemberBetLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下级游戏限制 的本地化字符串。
        /// </summary>
        public static string MemberGameLimit {
            get {
                return ResourceManager.GetString("MemberGameLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员资料 的本地化字符串。
        /// </summary>
        public static string MemberInfo {
            get {
                return ResourceManager.GetString("MemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会员输赢 的本地化字符串。
        /// </summary>
        public static string MemberWL {
            get {
                return ResourceManager.GetString("MemberWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中部 的本地化字符串。
        /// </summary>
        public static string Middle {
            get {
                return ResourceManager.GetString("Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小 的本地化字符串。
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期一 的本地化字符串。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 净值 的本地化字符串。
        /// </summary>
        public static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 净金额 的本地化字符串。
        /// </summary>
        public static string NetAmount {
            get {
                return ResourceManager.GetString("NetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能和原密码一致 的本地化字符串。
        /// </summary>
        public static string NewPwdCantEqualsOlds {
            get {
                return ResourceManager.GetString("NewPwdCantEqualsOlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一限制 的本地化字符串。
        /// </summary>
        public static string NextLimit {
            get {
                return ResourceManager.GetString("NextLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有开奖号码 的本地化字符串。
        /// </summary>
        public static string NoLotteryNum {
            get {
                return ResourceManager.GetString("NoLotteryNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您没有访问该页面的权限! 的本地化字符串。
        /// </summary>
        public static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北部 的本地化字符串。
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未接受 的本地化字符串。
        /// </summary>
        public static string NotAccept {
            get {
                return ResourceManager.GetString("NotAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未关盘 的本地化字符串。
        /// </summary>
        public static string NotCloseTime {
            get {
                return ResourceManager.GetString("NotCloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此路不通 -_- ! 的本地化字符串。
        /// </summary>
        public static string NoWay {
            get {
                return ResourceManager.GetString("NoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号码 的本地化字符串。
        /// </summary>
        public static string Num {
            get {
                return ResourceManager.GetString("Num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号码统计 的本地化字符串。
        /// </summary>
        public static string NumberStatistics {
            get {
                return ResourceManager.GetString("NumberStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字通配符 的本地化字符串。
        /// </summary>
        public static string NumberWildcard {
            get {
                return ResourceManager.GetString("NumberWildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单双 的本地化字符串。
        /// </summary>
        public static string OddEven {
            get {
                return ResourceManager.GetString("OddEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单头 的本地化字符串。
        /// </summary>
        public static string OddHead {
            get {
                return ResourceManager.GetString("OddHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单尾 的本地化字符串。
        /// </summary>
        public static string OddLast {
            get {
                return ResourceManager.GetString("OddLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单单 的本地化字符串。
        /// </summary>
        public static string OddOdd {
            get {
                return ResourceManager.GetString("OddOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赔率 的本地化字符串。
        /// </summary>
        public static string Odds {
            get {
                return ResourceManager.GetString("Odds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线会员数 的本地化字符串。
        /// </summary>
        public static string OnLine {
            get {
                return ResourceManager.GetString("OnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开盘时间 的本地化字符串。
        /// </summary>
        public static string OpenTime {
            get {
                return ResourceManager.GetString("OpenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注单列表 的本地化字符串。
        /// </summary>
        public static string OrderList {
            get {
                return ResourceManager.GetString("OrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号 的本地化字符串。
        /// </summary>
        public static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号 的本地化字符串。
        /// </summary>
        public static string OrderNum {
            get {
                return ResourceManager.GetString("OrderNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输赢结果 的本地化字符串。
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未结算 的本地化字符串。
        /// </summary>
        public static string Outstanding {
            get {
                return ResourceManager.GetString("Outstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组 的本地化字符串。
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抱歉，您访问的页面地址有误，或者该页面不存在。 的本地化字符串。
        /// </summary>
        public static string PageNotExist {
            get {
                return ResourceManager.GetString("PageNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级总佣金 的本地化字符串。
        /// </summary>
        public static string ParentComm {
            get {
                return ResourceManager.GetString("ParentComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误 的本地化字符串。
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择 的本地化字符串。
        /// </summary>
        public static string PleaseSelecte {
            get {
                return ResourceManager.GetString("PleaseSelecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的游戏玩法 的本地化字符串。
        /// </summary>
        public static string PleaseSelectedCorrectGameType {
            get {
                return ResourceManager.GetString("PleaseSelectedCorrectGameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个游戏玩法 的本地化字符串。
        /// </summary>
        public static string PleaseSelectGamePlayWay {
            get {
                return ResourceManager.GetString("PleaseSelectGamePlayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速下单 的本地化字符串。
        /// </summary>
        public static string QuickBet {
            get {
                return ResourceManager.GetString("QuickBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一旦删除，不可恢复，确定删除吗？ 的本地化字符串。
        /// </summary>
        public static string ReallyDelete {
            get {
                return ResourceManager.GetString("ReallyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地区 的本地化字符串。
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重 置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新结算 的本地化字符串。
        /// </summary>
        public static string ReSettle {
            get {
                return ResourceManager.GetString("ReSettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包组 的本地化字符串。
        /// </summary>
        public static string Roll {
            get {
                return ResourceManager.GetString("Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包组7 的本地化字符串。
        /// </summary>
        public static string Roll7 {
            get {
                return ResourceManager.GetString("Roll7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包组过关 的本地化字符串。
        /// </summary>
        public static string RollParlay {
            get {
                return ResourceManager.GetString("RollParlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受投注 的本地化字符串。
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期六 的本地化字符串。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开奖时间 的本地化字符串。
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字2 的本地化字符串。
        /// </summary>
        public static string SecondNum {
            get {
                return ResourceManager.GetString("SecondNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保证金 的本地化字符串。
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结算 的本地化字符串。
        /// </summary>
        public static string Settle {
            get {
                return ResourceManager.GetString("Settle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分成组 的本地化字符串。
        /// </summary>
        public static string ShareGroup {
            get {
                return ResourceManager.GetString("ShareGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分成 的本地化字符串。
        /// </summary>
        public static string ShareRate {
            get {
                return ResourceManager.GetString("ShareRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分成限制 的本地化字符串。
        /// </summary>
        public static string ShareRateLimit {
            get {
                return ResourceManager.GetString("ShareRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分成输赢 的本地化字符串。
        /// </summary>
        public static string ShareWL {
            get {
                return ResourceManager.GetString("ShareWL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注单号 的本地化字符串。
        /// </summary>
        public static string SheetNum {
            get {
                return ResourceManager.GetString("SheetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小 的本地化字符串。
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 南部 的本地化字符串。
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结单 的本地化字符串。
        /// </summary>
        public static string Statement {
            get {
                return ResourceManager.GetString("Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计 的本地化字符串。
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止投注限制 的本地化字符串。
        /// </summary>
        public static string StopAcceptBet {
            get {
                return ResourceManager.GetString("StopAcceptBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提 交 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交数据有错,请检查! 的本地化字符串。
        /// </summary>
        public static string SubmitDataError {
            get {
                return ResourceManager.GetString("SubmitDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子账户 的本地化字符串。
        /// </summary>
        public static string SubUser {
            get {
                return ResourceManager.GetString("SubUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期天 的本地化字符串。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级总代 的本地化字符串。
        /// </summary>
        public static string Super {
            get {
                return ResourceManager.GetString("Super", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Suspended {
            get {
                return ResourceManager.GetString("Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统维护中 的本地化字符串。
        /// </summary>
        public static string SystemMaintenance {
            get {
                return ResourceManager.GetString("SystemMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标 的本地化字符串。
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字3 的本地化字符串。
        /// </summary>
        public static string ThirdNum {
            get {
                return ResourceManager.GetString("ThirdNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本月 的本地化字符串。
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本周 的本地化字符串。
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期四 的本地化字符串。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间 的本地化字符串。
        /// </summary>
        public static string TimeLeft {
            get {
                return ResourceManager.GetString("TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统正忙，请稍候再试! 的本地化字符串。
        /// </summary>
        public static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到 的本地化字符串。
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总输赢 的本地化字符串。
        /// </summary>
        public static string ToalWinLost {
            get {
                return ResourceManager.GetString("ToalWinLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日开奖公司 的本地化字符串。
        /// </summary>
        public static string TodayLotteryCompany {
            get {
                return ResourceManager.GetString("TodayLotteryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今日跌水 的本地化字符串。
        /// </summary>
        public static string TodayWater {
            get {
                return ResourceManager.GetString("TodayWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 明日跌水 的本地化字符串。
        /// </summary>
        public static string TomorrowDropWater {
            get {
                return ResourceManager.GetString("TomorrowDropWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计 的本地化字符串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总金额 的本地化字符串。
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总下注额 的本地化字符串。
        /// </summary>
        public static string TotalBetAmount {
            get {
                return ResourceManager.GetString("TotalBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总佣金 的本地化字符串。
        /// </summary>
        public static string TotalCommission {
            get {
                return ResourceManager.GetString("TotalCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期二 的本地化字符串。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下注额 的本地化字符串。
        /// </summary>
        public static string Turnover {
            get {
                return ResourceManager.GetString("Turnover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十二生肖 的本地化字符串。
        /// </summary>
        public static string TwelveZodiac {
            get {
                return ResourceManager.GetString("TwelveZodiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新开奖公司 的本地化字符串。
        /// </summary>
        public static string UpdateLotteryCompany {
            get {
                return ResourceManager.GetString("UpdateLotteryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最终限制 的本地化字符串。
        /// </summary>
        public static string UpperLimit {
            get {
                return ResourceManager.GetString("UpperLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户名已存在 的本地化字符串。
        /// </summary>
        public static string UserAlreadyExist {
            get {
                return ResourceManager.GetString("UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录帐号 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的账户已被锁定,如需解锁,请联系您的上级! 的本地化字符串。
        /// </summary>
        public static string UserWasLock {
            get {
                return ResourceManager.GetString("UserWasLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误! 的本地化字符串。
        /// </summary>
        public static string VerifyCodeError {
            get {
                return ResourceManager.GetString("VerifyCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 越南十二生肖 的本地化字符串。
        /// </summary>
        public static string VietnameseZodiac {
            get {
                return ResourceManager.GetString("VietnameseZodiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 越南彩2 的本地化字符串。
        /// </summary>
        public static string VietnamLottery {
            get {
                return ResourceManager.GetString("VietnamLottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额 的本地化字符串。
        /// </summary>
        public static string Wager {
            get {
                return ResourceManager.GetString("Wager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 星期三 的本地化字符串。
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎您 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赢 的本地化字符串。
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输赢 的本地化字符串。
        /// </summary>
        public static string WinLost {
            get {
                return ResourceManager.GetString("WinLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败,请稍候再试,或尝试联系您的上级或管理员! 的本地化字符串。
        /// </summary>
        public static string WrongMessage {
            get {
                return ResourceManager.GetString("WrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 的本地化字符串。
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您可以 的本地化字符串。
        /// </summary>
        public static string YouCan {
            get {
                return ResourceManager.GetString("YouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的密码 的本地化字符串。
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 十二生肖 的本地化字符串。
        /// </summary>
        public static string Zodiac {
            get {
                return ResourceManager.GetString("Zodiac", resourceCulture);
            }
        }
    }
}
